language: python
python:
    - "3.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"
        - $HOME/.cache/pip

env:
    - PLATFORMIO_CI_SRC=RFLink


install:
    - pip install -U platformio
    - pio update
    - platformio lib install

script:
    - pio ci --board=esp32doit-devkit-v1 --project-option="lib_deps=PubSubClient,Wire,SPI"