name: Rflink Build Tests

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        pio update


    - name: ESP32_none_enabled
      run: |
        pio run --project-conf .travis.platformio.ini --environment ESP32_none_enabled
    - name: ESP32_sw
      run: |
        pio run --project-conf .travis.platformio.ini --environment ESP32_sw


    - name: D1_none_enabled
      run: |
        pio run --project-conf .travis.platformio.ini --environment D1_none_enabled
    - name: D1_sw
      run: |
        pio run --project-conf .travis.platformio.ini --environment D1_sw

    - name: Copy firmwares in 1 place
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        mkdir firmwares
        cp .pio/build/ESP32_sw/firmware.bin firmwares/esp32-firmware.bin
        cp .pio/build/ESP32_sw/partitions.bin firmwares/esp32-partitions.bin
        cp .pio/build/D1_sw/firmware.bin firmwares/esp8266-firmware.bin
        cd firmwares
        wget https://raw.githubusercontent.com/espressif/arduino-esp32/master/tools/partitions/boot_app0.bin
        wget https://raw.githubusercontent.com/espressif/arduino-esp32/master/tools/sdk/bin/bootloader_dio_40m.bin
        cd ..

    - name: Publish firmware
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Development Build"
        files: |
          firmwares/*.bin




